# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='attr1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='attr2',
            field=models.TextField(default=None, null=True),
        ),
    ]
